version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - "app-network" 

  backend:
    build: 
      context: ./web-api
    ports:
      - "3001:3001"
    environment:
      - HOST = 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
